### ISSUE TITLE
OpenToonz для XP

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/morevna-club#17]
@blackwarthog См. обсуждение здесь - http://support.morevnaproject.org/topics/398-ne-zapuskaetsya-open-toonz-posle-ustanovki-oshibka-tochka-vhoda-ne-najdena/

**Comment by blackwarthog** [comment]
![morevna-episode-3 0 1 mp4](https://user-images.githubusercontent.com/5143743/29487026-807d4722-8525-11e7-9541-be2fafd711bc.png)

**Comment by morevnaproject** [comment]
Ну, вобще да. ^__^" 

Я думал, что было бы удобно иметь support-форум для RenderChan (международный) и OpenToonz (на русском). Чтобы туда отправлять русских пользователей ОТ у которых вопросы (не баги, а вопросы). А то они в ВК пишут. ^___^"

Тебе не надо следиь за Support'ом - идея была в том, что там будет сидеть @Agnyy и Ко.

**Comment by morevnaproject** [comment]
Исходное сообщение:

> Здравствуйте. Скачал OpenToonz-1.1.3-morevna-win-32bit (win XP Pro Servise Pack 3), программа не запускается, выдает ошибку - точка входа в процедуру strtok_s не найдена в библиотеке DLL msvcrt.dll..............перезагрузка пк, переустановка программы - не помогают..................замена msvcrt.dll  на версию 32bit 
Windows XP msvcrt.dll 
v. 7.0.2600.5512 так же не помогла........Что можно сделать в данной ситуации?

![unnamed](https://user-images.githubusercontent.com/332868/33018000-2366e8cc-ce27-11e7-927d-6d3f24ee60ea.png)

**Comment by morevnaproject** [comment]
https://vk.com/wall-138090216_205

**Comment by morevnaproject** [comment]
Последние версии QT не работают с Windows XP, поэтому OpenToonz работать под XP не будет.
