### ISSUE TITLE
Перевести субтитры на русский для Bazza

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/morevna-club#27]
Текст на английском - https://raw.githubusercontent.com/4232/4232/master/4232.en.vtt

Ссылка на видео - https://vk.com/im?msgid=66134&peers=224050647&sel=26143029

**Comment by morevnaproject** [comment]
/remind me about the thing in 18 hours

**Comment by morevnaproject** [comment]
/remind me about the thing in 68 hours

**Comment by Stas-Kholodilin** [comment]
Done.
