### ISSUE TITLE
113-a2 залить Ивана

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/morevna-club#46]
файл "/ep03/113-a2/113-a2-v2-3.kra"

образцы цветов в "/ep03/color/0-ref-ivan.png"

**Comment by Stas-Kholodilin** [comment]
Готово, только там не очень понятно для меня. (Где, что и так далее). Основное все закрасил. Думаю Настя там разберется.

**Comment by morevnaproject** [comment]
Отлично, Стас! Спасибо! ^__^
