### ISSUE TITLE
OpenToonz вылетает при выборе инструмента "Заливка" в векторных уровнях. (гиф)

### ISSUE THREAD

**Issue by beeheemooth** [morevnaproject/morevna-club#54]
Это в сегодняшнем релизе.
![ezgif-3-cde85ffb8a](https://user-images.githubusercontent.com/25724133/34687816-8e12e9b6-f4b8-11e7-9fb8-25d41f028db6.gif)

**Comment by morevnaproject** [comment]
Пока что не смог воспроизвести этот баг на линуксе. Я посмотрю на windows, как будет возможность.

/remind me abou this issue in 36 hours

**Comment by beeheemooth** [comment]
Мне удалось определить, в каком случае происходит вылет.  И это происходит не только в Morevna Edition.

Это случается после запуска программы, когда после создания (первого) векторного уровня (первой сцены) активируется Fill Tool и он находится в режиме Line. Если Fill Tool при запуске находится в любом из остальных режимов (Areas, Lines&Areas) то вылета не происходит.

Если сцена или уровень не первые после запуска, то вылет также не происходит, независимо от того в каком режиме находится Fill Tool.

**Comment by beeheemooth** [comment]
Если что, то я написал и сюда:
https://github.com/opentoonz/opentoonz/issues/1737

**Comment by morevnaproject** [comment]
Спасибо, Юрий! Рад, что удалось локализовать проблему. ^__^ Включим в следующую сборку как только будет возможность.
