### ISSUE TITLE
OpenToonz. В растровых уровнях не сохраняются кадры с суффиксами.

### ISSUE THREAD

**Issue by beeheemooth** [morevnaproject/morevna-club#56]
Эта проблема есть во всех версиях, но поскольку она связана с растром, я пишу сюда.
Кадры с суффиксами (a, b ...) например 2a, 2b ... не отображаются при открытии сохранённой сцены, в Level Strip их просто нет.

**Comment by morevnaproject** [comment]
Подтверждаю. Проблема критическая - тоже столкнулись. Пока что приходится "лечить" сцены переименовыванием файлов. Но это. конечно, не выход.

**Comment by morevnaproject** [comment]
Пока Иван разбирается спроблемой, я нашёл как её обойти.
Зайди в меню "File" -> "Preferences" и там перейди в раздел "Drawing". В списке "Autocreation" поставь "Enabled" вместо "Use XSheet as animation sheet"

![screenshot_006](https://user-images.githubusercontent.com/332868/36063409-0671f446-0eaf-11e8-9ee8-b37d745ff56d.png)

**Comment by beeheemooth** [comment]
У меня совсем вылетело из головы, что полгода назад я постил аналогичную проблему с исчезновением кадров в Toonz Raster, и она была решена: https://github.com/opentoonz/opentoonz/issues/1312
В нынешних растровых уровнях тоже происходит вылет после Autorenumber, Save и Reload. Возможно решение проблемы в Toonz Raster поможет и в растровых уровнях.

**Comment by morevnaproject** [comment]
Пофиксено здесь - https://github.com/opentoonz/opentoonz/pull/1833
