### ISSUE TITLE
OpenToonz. Вылет программы при использовании ластика в растровых уровнях (гиф)

### ISSUE THREAD

**Issue by beeheemooth** [morevnaproject/morevna-club#58]
_"Чтобы поймать крэш, нужно думать как крэш..."_ :)

Вот один из них. Чтобы воспроизвести его сделайте последовательно следующие шаги:
1. Находясь на растровом уровне выберите Eraser Tool  и измените его тип на Freehand (это делается для того, чтобы при следующем запуске ОТ ластик уже находился в режиме Freehand, и его не нужно было переключать вручную)
1. Пререзапустите OpenToonz. 
2. Создайте новый растровый уровень
3. Используя MyPaint ситль нарисуйте что-то кистью.
4. Выберите ХОТКЕЕМ (это важно!) ластик (Eraser Tool) и он уже должен быть в режиме Freehand.
5. Сотрите фрагмент пользуясь этим режимом.
6. Отмените действие (Undo). Программа вылетает.

![ezgif-1-37d5010282](https://user-images.githubusercontent.com/25724133/36494012-9906c588-1739-11e8-99e1-ca2435990b68.gif)

**Comment by beeheemooth** [comment]
Уже исправили!
https://github.com/opentoonz/opentoonz/issues/1821#issuecomment-367553238

**Comment by morevnaproject** [comment]
Хорошо. ^__^

Если баг в оспроизводится в официальной версии, то лучше сразу отсылать в официальный багтракер. Мы обычно занимаемся только багами, которые специфичны для Morevna Edition. ^__^

**Comment by beeheemooth** [comment]
Сначала я подумал, что это может быть связано с MyPaint, но видимо это баг был ещё до-mypaint-овского периода.
